# Generated by Django 5.0.4 on 2024-04-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100)),
                ('descripcionproducto', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cantidad', models.IntegerField()),
                ('especificaciones', models.TextField()),
                ('imagenP', models.ImageField(upload_to='static/img_producto/')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='static/img_producto/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='static/img_producto/')),
            ],
        ),
    ]
